Clean up

diff --git a/auto-update b/auto-update
--- a/auto-update
+++ b/auto-update
@@ -466,77 +466,8 @@ update() {
 keepsudoalive
 
 if [ "$1" = "-a" -o "$1" = "--all" ]; then
-	if [ -z "$OAUTH_TOKEN" ]; then
-		echo "For --all to work, export OAUTH_TOKEN=\"token\""
-		echo "where \"token\" is a github authentication token"
-		echo "generated at https://github.com/settings/token"
-		exit 1
-	fi
-	OURDIR="$(dirname $0)"
-	# Packages that have known breakages in the current version and need
-	# to be updated if and only if there's a newer release fixing the
-	# issue blocking the update
-	BLACKLIST="sqlite"
-	# Packages that are known to break when auto-updated
-	# (e.g. perl doesn't like having Release: reset)
-	BLACKLIST="$BLACKLIST perl"
-	# Repositories that are archived for historic reasons
-	# but don't contain anything expected to be buildable
-	# ever again
-	BLACKLIST="$BLACKLIST consonance wxPythonGTK python2.4 python2.4-ldap python2.4-yaml python2.4-mysql python2.4-openid python2.4-wicked python2.4-imaging python2.4-libxml2 python2.4-feedparser python2.4-setuptools python2.4-virtualenv python2.4-elementtree"
-	# Repositories that need to be maintained manually
-	BLACKLIST="$BLACKLIST distro-release lsb-release"
-	# Repositories containing abandoned projects that we still distribute
-	# because they may be useful to some, but that don't have a working
-	# upstream website or repository to check for updates
-	BLACKLIST="$BLACKLIST clamz libifp"
-	# Repositories that contain active projects that should be updated at
-	# some point, but only after sorting out dependencies (e.g. Java/mvn
-	# packaging)
-	BLACKLIST="$BLACKLIST zookeeper"
-	# Repositories that should not be updated individually, but as
-	# part of a larger package set at the same time (e.g. KDE)
-	for i in qt qt6 kf kf6 plasma6 pd kapps kapps6 plasma-mobile-gear; do
-		for j in $(cat "$OURDIR/$i.buildlist"); do
-			BLACKLIST="$BLACKLIST $(echo $j |sed -e 's,openmandriva/,,g')"
-		done
-	done
-
-	PACKAGES=""
-	PERPAGE=100
-	COUNT=0
-	START=""
-	org=OpenMandrivaAssociation
-	echo -n "Getting list of packages "
-	while true; do
-		echo -n .
-		QUERY="{\"query\": \"query {organization(login:\\\"$org\\\") { id name repositories(first:$PERPAGE $START) { edges { node { id name } cursor } pageInfo { endCursor hasNextPage } } } }\""
-		REPOS="$(curl -H "Authorization: token $OAUTH_TOKEN" -X POST -d "$QUERY" https://api.github.com/graphql 2>/dev/null)"
-		if [ -z "$REPOS" ]; then
-			 echo "$QUERY failed" >&2
-			 break
-		fi
-		for i in $(seq 0 $((PERPAGE-1))); do
-			R="$(echo $REPOS |json "['data']['organization']['repositories']['edges'][$i]['node']['name']").git"
-			if [ "$R" = ".git" ]; then
-				echo "No more repositories at $QUERY $i" >&2
-				break
-			fi
-			if [ "$R" = "abf-yml.git" -o "$R" = "secret-keys.git" -o "$R" = "OpenMandrivaAssociation.github.io.git" ]; then
-				# These repositories contain passwords and aren't public
-				# Since we aren't authenticated, can't mirror them
-				continue
-			fi
-			COUNT=$((COUNT+1))
-			PKG="$(echo $R |sed -e 's,\.git$,,')"
-			if ! echo " $BLACKLIST " |grep -q " $PKG "; then
-				PACKAGES="$PACKAGES $PKG"
-			fi
-		done
-		[ "$(echo $REPOS |json "['data']['organization']['repositories']['pageInfo']['hasNextPage']")" != "True" ] && break
-		START="after:\\\"$(echo $REPOS |json "['data']['organization']['repositories']['pageInfo']['endCursor']")\\\""
-	done
-	echo
+	# This is now the default behavior and the switch is
+	# deprecated. Ignore it for now.
 	shift
 fi
 
@@ -558,12 +489,78 @@ if [ -z "$PACKAGES" ]; then
 	if [ "$#" -gt 0 ]; then
 		PACKAGES="$@"
 	else
-		# Packages known to work under normal conditions...
-		# Listed in alphabetic order, except when one update typically
-		# depends on another (e.g. sogo needs to go after sope)
-		# Also, larger blocks of related packages (e.g. X11) may be grouped
-		# together
-		PACKAGES="a2ps acmetool acpica adcli adwaita-icon-theme ags aisleriot alsa-lib alsa-utils alsa-tools appstream-glib arping asio babeltrace bino bison bmake chromium-browser-dev chromium-browser-stable cmake cups-filters curl dhcpcd diffutils digikam e2fsprogs fann ffmpeg firefox flac freetds freetype gdbm git gnupg gnustep-make gnustep-base gnustep-gui grantlee gsl gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly guile gzip harfbuzz imagemagick imagemagick6 indilib iproute2 itstool iw joe kaffeine krb5 ladspa lame libaacs libbsd libbluray libcdio libcdr libcmis libdmtx libdrm libdvbpsi libdvdread libdvdnav libdvdcss libixion libogg liborcus libshout libqalculate libraw libssh2 libtiff libunistring libvisio libvorbis libzip man-pages mercurial mesa microcode-intel mpg123 nasm nettle nfs-utils nss mdds mpfr mpv onig openttd optipng patch pciutils physfs pigz polkit poppler pth python-twisted qpdf redis rspamd rsync scons smplayer sope sogo strace talloc tevent tdb usbutils ldb samba sqlite subversion tor vim vorbis-tools warzone2100 xfsprogs xmlrpc-epi xmlsec1 x11-driver-input-acecad x11-driver-input-aiptek x11-driver-input-citron x11-driver-input-evdev x11-driver-input-fpit x11-driver-input-hyperpen x11-driver-input-joystick x11-driver-input-keyboard x11-driver-input-libinput x11-driver-input-mouse x11-driver-input-mutouch x11-driver-input-penmount x11-driver-input-synaptics x11-driver-input-vmmouse x11-driver-input-void x11-driver-video-amdgpu x11-driver-video-apm x11-driver-video-ark x11-driver-video-ast x11-driver-video-ati x11-driver-video-chips x11-driver-video-dummy x11-driver-video-fbdev x11-driver-video-freedreno x11-driver-video-geode x11-driver-video-glint x11-driver-video-i128 x11-driver-video-i740 x11-driver-video-intel x11-driver-video-mach64 x11-driver-video-neomagic x11-driver-video-newport x11-driver-video-nouveau x11-driver-video-nv x11-driver-video-omap x11-driver-video-openchrome x11-driver-video-opentegra x11-driver-video-qxl x11-driver-video-r128 x11-driver-video-rendition x11-driver-video-s3 x11-driver-video-s3virge x11-driver-video-savage x11-driver-video-siliconmotion x11-driver-video-sis x11-driver-video-sisusb x11-driver-video-tdfx x11-driver-video-tga x11-driver-video-trident x11-driver-video-tseng x11-driver-video-v4l x11-driver-video-vesa x11-driver-video-vmware x11-driver-video-voodoo x11-driver-video-xgixp libdmx libfontenc libfs libice liblbxutil libpciaccess libpthread-stubs libsm libx11 libxau libxaw libxcomposite libxcursor libxdamage libxdmcp libxevie libxext libxfixes libxfont libxfont2 libxfontcache libxft libxi libxinerama libxkbfile libxkbui libxmu libxpm libxpresent libxrandr libxrender libxres libxscrnsaver libxshmfence libxt libxtrap libxtst libxv libxvmc libxxf86dga libxxf86misc pixman x11-xtrans-devel appres bdftopcf beforelight bitmap editres fonttosfnt fslsfonts fstobdf grandr iceauth ico intel-gpu-tools lbxproxy listres luit mkcomposecache mkfontdir mkfontscale oclock proxymngr rendercheck rgb rstart sessreg setxkbmap showfont smproxy twm viewres x11perf xauth xbacklight xbiff x11-data-bitmaps xcalc xclipboard xclock xcmsdb xcompmgr xconsole xcursorgen xdbedizzy xditview xdm xdpyinfo xdriinfo xedit xev xeyes xf86dga xfd xfindproxy xfontsel xfs xfsinfo xfwp xgamma xgc xhost xinit xinput xkbcomp xkbevd xkbprint xkbutils xkill xload xlogo xlsatoms xlsclients xlsfonts xmag xman xmessage xmh xmodmap xmore xpr xprop xrandr xrdb xrefresh xrx xscope xset xsetmode xsetpointer xsetroot xsm xstdcmap xtrap xvidtune xvinfo xwd xwininfo xwud xkeyboard-config x11-server gccmakedep imake lndir makedepend x11-util-macros x11-util-cf-files libxcb xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm wine atk1.0 atkmm at-spi2-core at-spi2-atk dconf libcroco0.6 librsvg babl gegl cogl clutter libchamplain libopenraw libpeas libsigc-2.0 libsigc-3.0 glib2.0 glibmm gssdp gupnp gupnp-igd libnice farstream gsettings-desktop-schemas gtkmm3.0 gtksourceview gedit gvfs yelp libmbim libqmi ModemManager NetworkManager pangomm whois htop nginx networkmanager-pptp firewalld stunnel ssr proj"
+		if [ -z "$OAUTH_TOKEN" ]; then
+			echo "For updating all packages to work,"
+			echo "	export OAUTH_TOKEN=\"token\""
+			echo "where \"token\" is a github authentication token"
+			echo "generated at https://github.com/settings/token"
+			exit 1
+		fi
+		OURDIR="$(dirname $0)"
+		# Packages that have known breakages in the current version and need
+		# to be updated if and only if there's a newer release fixing the
+		# issue blocking the update
+		BLACKLIST="sqlite"
+		# Packages that are known to break when auto-updated
+		# (e.g. perl doesn't like having Release: reset)
+		BLACKLIST="$BLACKLIST perl"
+		# Repositories that are archived for historic reasons
+		# but don't contain anything expected to be buildable
+		# ever again
+		BLACKLIST="$BLACKLIST consonance wxPythonGTK python2.4 python2.4-ldap python2.4-yaml python2.4-mysql python2.4-openid python2.4-wicked python2.4-imaging python2.4-libxml2 python2.4-feedparser python2.4-setuptools python2.4-virtualenv python2.4-elementtree"
+		# Repositories that need to be maintained manually
+		BLACKLIST="$BLACKLIST distro-release lsb-release"
+		# Repositories containing abandoned projects that we still distribute
+		# because they may be useful to some, but that don't have a working
+		# upstream website or repository to check for updates
+		BLACKLIST="$BLACKLIST clamz libifp"
+		# Repositories that contain active projects that should be updated at
+		# some point, but only after sorting out dependencies (e.g. Java/mvn
+		# packaging)
+		BLACKLIST="$BLACKLIST zookeeper"
+		# Repositories that should not be updated individually, but as
+		# part of a larger package set at the same time (e.g. KDE)
+		for i in qt qt6 kf kf6 plasma6 pd kapps kapps6 plasma-mobile-gear; do
+			for j in $(cat "$OURDIR/$i.buildlist"); do
+				BLACKLIST="$BLACKLIST $(echo $j |sed -e 's,openmandriva/,,g')"
+			done
+		done
+
+		PACKAGES=""
+		PERPAGE=100
+		COUNT=0
+		START=""
+		org=OpenMandrivaAssociation
+		echo -n "Getting list of packages "
+		while true; do
+			echo -n .
+			QUERY="{\"query\": \"query {organization(login:\\\"$org\\\") { id name repositories(first:$PERPAGE $START) { edges { node { id name } cursor } pageInfo { endCursor hasNextPage } } } }\""
+			REPOS="$(curl -H "Authorization: token $OAUTH_TOKEN" -X POST -d "$QUERY" https://api.github.com/graphql 2>/dev/null)"
+			if [ -z "$REPOS" ]; then
+				 echo "$QUERY failed" >&2
+				 break
+			fi
+			for i in $(seq 0 $((PERPAGE-1))); do
+				R="$(echo $REPOS |json "['data']['organization']['repositories']['edges'][$i]['node']['name']").git"
+				if [ "$R" = ".git" ]; then
+					echo "No more repositories at $QUERY $i" >&2
+					break
+				fi
+				if [ "$R" = "abf-yml.git" -o "$R" = "secret-keys.git" -o "$R" = "OpenMandrivaAssociation.github.io.git" ]; then
+					# These repositories contain passwords and aren't public
+					# Since we aren't authenticated, can't mirror them
+					continue
+				fi
+				COUNT=$((COUNT+1))
+				PKG="$(echo $R |sed -e 's,\.git$,,')"
+				if ! echo " $BLACKLIST " |grep -q " $PKG "; then
+					PACKAGES="$PACKAGES $PKG"
+				fi
+			done
+			[ "$(echo $REPOS |json "['data']['organization']['repositories']['pageInfo']['hasNextPage']")" != "True" ] && break
+			START="after:\\\"$(echo $REPOS |json "['data']['organization']['repositories']['pageInfo']['endCursor']")\\\""
+		done
+		echo
 	fi
 fi
 
