Fix up rebuilddeps

diff --git a/rebuilddeps b/rebuilddeps
--- a/rebuilddeps
+++ b/rebuilddeps
@@ -34,29 +34,30 @@ while read r; do
 			echo "NOT $r"
 			continue
 		fi
-		rm -rf ${r}
-		git clone git@github.com:OpenMandrivaAssociation/${r}.git || error clone $r
-		cd ${r}
-		OLDRELEASE="$(grep -i '^Release[[:space:]]*:' *.spec |cut -d: -f2- |xargs echo)"
-		if echo ${OLDRELEASE} |grep -q '}'; then
-			NUMREL=`echo $OLDRELEASE |rev |cut -d'}' -f1 |rev`
-			RELEASE=`echo $OLDRELEASE |sed -e "s,}[^}]*\$,}$((NUMREL+1)),"`
-		elif echo ${OLDRELEASE} |grep -q '\.'; then
-			NUMREL=`echo $OLDRELEASE |rev |cut -d'.' -f1 |rev`
-			RELEASE=`echo $OLDRELEASE |sed -e "s,\.[^.]*\$,.$((NUMREL+1)),"`
-		else
-			RELEASE=$((OLDRELEASE+1))
-		fi
-		if [ "$RELEASE" = "$OLDRELEASE" ]; then
-			error "Could not determine new release number for $r"
-			exit 1
-		fi
-
-		sed -i -e "s,^\(Release.*:.*\)${OLDRELEASE},\1${RELEASE}," *.spec
-		git commit -am "$REASON"
-		git push origin master
-		cd ..
-		BUILDLIST="$BUILDLIST openmandriva/$r"
 	fi
+
+	rm -rf ${r}
+	git clone git@github.com:OpenMandrivaAssociation/${r}.git || error clone $r
+	cd ${r}
+	OLDRELEASE="$(grep -i '^Release[[:space:]]*:' *.spec |cut -d: -f2- |xargs echo)"
+	if echo ${OLDRELEASE} |grep -q '}'; then
+		NUMREL=`echo $OLDRELEASE |rev |cut -d'}' -f1 |rev`
+		RELEASE=`echo $OLDRELEASE |sed -e "s,}[^}]*\$,}$((NUMREL+1)),"`
+	elif echo ${OLDRELEASE} |grep -q '\.'; then
+		NUMREL=`echo $OLDRELEASE |rev |cut -d'.' -f1 |rev`
+		RELEASE=`echo $OLDRELEASE |sed -e "s,\.[^.]*\$,.$((NUMREL+1)),"`
+	else
+		RELEASE=$((OLDRELEASE+1))
+	fi
+	if [ "$RELEASE" = "$OLDRELEASE" ]; then
+		error "Could not determine new release number for $r"
+	fi
+
+	sed -i -e "s,^\(Release.*:.*\)${OLDRELEASE},\1${RELEASE}," *.spec
+	git commit -am "$REASON"
+	git push origin master
+	cd ..
+
+	BUILDLIST="$BUILDLIST openmandriva/$r"
 done < <(dnf repoquery --whatrequires "$DEP" --qf '%{sourcerpm}' |rev |cut -d- -f3- |rev |sort |uniq)
-abf chain_build -a znver1 -a aarch64 -a x86_64 -b master --no-extra-tests --update-type enhancement $BUILDLIST
+echo $BUILDLIST | abf chain_build -a znver1 -a aarch64 -a x86_64 -b master --no-extra-tests --update-type enhancement -i /dev/stdin
