Add rebuilddeps flag for silent rebuilds

diff --git a/rebuilddeps b/rebuilddeps
--- a/rebuilddeps
+++ b/rebuilddeps
@@ -16,6 +16,13 @@ D=$(realpath $(dirname "$0"))
 
 is_qt6=false
 
+if [ "$1" = "-r" ]; then
+	DONT_BUMP=true
+	shift
+else
+	DONT_BUMP=false
+fi
+
 DEP="$1"
 shift
 if [ "$#" -gt 0 ]; then
@@ -37,27 +44,29 @@ while read r; do
 		fi
 	fi
 
-	rm -rf ${r}
-	git clone git@github.com:OpenMandrivaAssociation/${r}.git || error clone $r
-	cd ${r}
-	OLDRELEASE="$(grep -i '^Release[[:space:]]*:' *.spec |cut -d: -f2- |xargs echo)"
-	if echo ${OLDRELEASE} |grep -q '}'; then
-		NUMREL=`echo $OLDRELEASE |rev |cut -d'}' -f1 |rev`
-		RELEASE=`echo $OLDRELEASE |sed -e "s,}[^}]*\$,}$((NUMREL+1)),"`
-	elif echo ${OLDRELEASE} |grep -q '\.'; then
-		NUMREL=`echo $OLDRELEASE |rev |cut -d'.' -f1 |rev`
-		RELEASE=`echo $OLDRELEASE |sed -e "s,\.[^.]*\$,.$((NUMREL+1)),"`
-	else
-		RELEASE=$((OLDRELEASE+1))
-	fi
-	if [ "$RELEASE" = "$OLDRELEASE" ]; then
-		error "Could not determine new release number for $r"
-	fi
+	if ! $DONT_BUMP; then
+		rm -rf ${r}
+		git clone git@github.com:OpenMandrivaAssociation/${r}.git || error clone $r
+		cd ${r}
+		OLDRELEASE="$(grep -i '^Release[[:space:]]*:' *.spec |cut -d: -f2- |xargs echo)"
+		if echo ${OLDRELEASE} |grep -q '}'; then
+			NUMREL=`echo $OLDRELEASE |rev |cut -d'}' -f1 |rev`
+			RELEASE=`echo $OLDRELEASE |sed -e "s,}[^}]*\$,}$((NUMREL+1)),"`
+		elif echo ${OLDRELEASE} |grep -q '\.'; then
+			NUMREL=`echo $OLDRELEASE |rev |cut -d'.' -f1 |rev`
+			RELEASE=`echo $OLDRELEASE |sed -e "s,\.[^.]*\$,.$((NUMREL+1)),"`
+		else
+			RELEASE=$((OLDRELEASE+1))
+		fi
+		if [ "$RELEASE" = "$OLDRELEASE" ]; then
+			error "Could not determine new release number for $r"
+		fi
 
-	sed -i -e "s,^\(Release.*:.*\)${OLDRELEASE},\1${RELEASE}," *.spec
-	git commit -am "$REASON"
-	git push origin master
-	cd ..
+		sed -i -e "s,^\(Release.*:.*\)${OLDRELEASE},\1${RELEASE}," *.spec
+		git commit -am "$REASON"
+		git push origin master
+		cd ..
+	fi
 
 	BUILDLIST="$BUILDLIST openmandriva/$r"
 done < <(dnf --refresh repoquery --whatrequires "$DEP" --qf '%{sourcerpm}' |rev |cut -d- -f3- |rev |sort |uniq)
